# Generated by Django 4.2.4 on 2025-06-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(db_column='OWNER', max_length=100)),
                ('location', models.CharField(db_column='LOCATION', max_length=100)),
                ('case', models.CharField(db_column='CASE', max_length=100)),
                ('sku', models.CharField(db_column='SKU', max_length=100)),
                ('uom', models.CharField(db_column='UOM', max_length=20)),
                ('quantity', models.IntegerField(db_column='QUANTITY', default=1)),
                ('asn_number', models.CharField(db_column='ASNNUMBER', max_length=20)),
                ('line_number', models.CharField(db_column='LINENUMBER', max_length=6)),
                ('status', models.IntegerField(db_column='STATUS', default=1)),
                ('download_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], db_column='DOWNLOADSTATUS', default='no', max_length=3)),
                ('username', models.CharField(db_column='USERNAME', default='default_user', max_length=100)),
                ('created_date', models.DateTimeField(blank=True, db_column='ADDDATE', null=True)),
            ],
            options={
                'db_table': 'DOWNLOADINVENTORY',
            },
        ),
        migrations.CreateModel(
            name='InventoryCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(db_column='OWNER', max_length=100)),
                ('location', models.CharField(db_column='LOCATION', max_length=100)),
                ('case', models.CharField(db_column='CASE', max_length=100)),
                ('sku', models.CharField(db_column='SKU', max_length=100)),
                ('uom', models.CharField(db_column='UOM', max_length=20)),
                ('quantity', models.IntegerField(db_column='QUANTITY', default=1)),
                ('username', models.CharField(db_column='USERNAME', default='default_user', max_length=100)),
                ('created_date', models.DateTimeField(blank=True, db_column='ADDDATE', null=True)),
                ('status', models.IntegerField(db_column='STATUS', default=0)),
            ],
            options={
                'db_table': 'INVENTORYCAPTURE',
            },
        ),
        migrations.CreateModel(
            name='NextupNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Starting_Number', models.CharField(db_column='STARTINGNUMBER', max_length=50)),
                ('Ending_Number', models.CharField(db_column='ENDINGNUMBER', max_length=50)),
                ('Current_Number', models.CharField(db_column='CURRENTNUMBER', max_length=50)),
                ('Next_Number', models.CharField(db_column='NEXTNUMBER', max_length=50)),
                ('NUMBEROFLINES', models.IntegerField(db_column='NUMBEROFLINES', default=0)),
                ('created_date', models.DateTimeField(blank=True, db_column='ADDDATE', null=True)),
                ('updated_datetime', models.DateTimeField(blank=True, db_column='LASTLOGIN', null=True)),
                ('created_username', models.CharField(blank=True, db_column='CREATEDUSERNAME', max_length=100, null=True)),
                ('updated_username', models.CharField(blank=True, db_column='UPDATEDUSERNAME', max_length=100, null=True)),
                ('prefix', models.CharField(db_column='TYPE', default='ASN', max_length=10)),
            ],
            options={
                'db_table': 'NEXTUPNUMBER',
            },
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='USERNAME', default='default_user', max_length=100)),
                ('password', models.CharField(db_column='PASSWORD', max_length=100)),
                ('created_date', models.DateTimeField(blank=True, db_column='ADDDATE', null=True)),
                ('updated_datetime', models.DateTimeField(blank=True, db_column='LASTLOGIN', null=True)),
            ],
            options={
                'db_table': 'USERMASTER',
            },
        ),
    ]
