# Generated by Django 4.2.4 on 2025-06-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadinventory',
            name='created_date',
        ),
        migrations.AddField(
            model_name='downloadinventory',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, db_column='LASTLOGIN', null=True),
        ),
        migrations.AlterField(
            model_name='downloadinventory',
            name='username',
            field=models.CharField(db_column='USERNAME', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='username',
            field=models.CharField(db_column='USERNAME', max_length=100, unique=True),
        ),
    ]
