# Generated by Django 4.2.4 on 2025-06-12 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0002_remove_downloadinventory_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadinventory',
            name='updated_datetime',
        ),
        migrations.RemoveField(
            model_name='downloadinventory',
            name='username',
        ),
    ]
