# Generated by Django 4.2.4 on 2025-06-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0003_remove_downloadinventory_updated_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadinventory',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, db_column='LASTLOGIN', null=True),
        ),
        migrations.AddField(
            model_name='downloadinventory',
            name='updated_username',
            field=models.CharField(blank=True, db_column='UPDATEDUSERNAME', max_length=100, null=True),
        ),
    ]
