# Generated by Django 4.2.4 on 2025-06-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0004_downloadinventory_updated_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextupnumber',
            name='prefix',
            field=models.CharField(db_column='PREFIX', default='ASN', max_length=10),
        ),
    ]
