# Generated by Django 4.2.4 on 2025-06-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0005_alter_nextupnumber_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextupnumber',
            name='type',
            field=models.CharField(db_column='TYPE', default='ASN', max_length=50),
        ),
    ]
