# Generated by Django 4.2.4 on 2025-06-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0006_nextupnumber_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextupnumber',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
