# Generated by Django 5.2.3 on 2025-06-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventoryapp', '0007_alter_nextupnumber_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextupnumber',
            name='prefix',
            field=models.CharField(db_column='PREFIX', default='ASN', max_length=10),
        ),
    ]
